apiVersion: v1
kind: ConfigMap
metadata:
  name: clustercost-dashboard-config
  namespace: clustercost
data:
  config.yaml: |
    listenAddr: ":9090"
    grpcAddr: ":9091"
    defaultAgentToken: "global-secret-token"
    pollInterval: 0s
    disableHttpPolling: true
    agents:
      - name: "production-cluster"
        type: "k8s"
        baseUrl: "http://<agent-service-url>:8080" # Optional if only using gRPC for reporting
        token: "change-me-to-secure-token-1"
      - name: "staging-cluster"
        type: "k8s"
        token: "change-me-to-secure-token-2"
